#!/usr/bin/env bash
set -e

rm -f README.md
make
sed -i '' "s/var version = '.*';/var version = '$VERSION';/" index.js test/index.js
node --eval '
  var fs = require("fs");
  var pkg = require("./package.json");
  pkg.devDependencies["sanctuary-type-classes"] = process.env.VERSION;
  fs.writeFileSync("./package.json",
                   JSON.stringify(pkg, null, 2) + "\n",
                   {encoding: "utf8"});
'
git add LICENSE README.md index.js test/index.js
